---
displayName: NodeJS Express
description: NodeJS stack with NPM 6.14.6, NodeJS 12.18.4 and Express Web Application
tags: ["NodeJS", "NPM", "Express", "UBI8"]
icon: /images/type-node.svg
globalMemoryLimit: 2198Mi
