apiVersion: v2
publisher: eclipse
name: ideaIC-NOVNC
version: 2020.2.2
type: Che Editor
displayName:  IntelliJ IDEA Community Edition
title:  IntelliJ IDEA Community Edition (in browser using noVNC) as editor for Eclipse Che
description:  IntelliJ IDEA Community Edition running on the Web with noVNC
icon: https://resources.jetbrains.com/storage/products/intellij-idea/img/meta/intellij-idea_logo_300x300.png
category: Editor
repository: https://github.com/che-incubator/jetbrains-editor-images
firstPublicationDate: "2020-09-25"
spec:
  endpoints:
   -  name: "intellij"
      public: true
      targetPort: 8080
      attributes:
        protocol: http
        type: ide
        discoverable: false
        path: /vnc.html?resize=remote&autoconnect=true&reconnect=true
  containers:
   - name: ideaic-novnc
     image: "quay.io/che-incubator/che-editor-intellij-community:latest"
     mountSources: true
     volumes:
         - mountPath: "/JetBrains/IdeaIC"
           name: idea-configuration
     ports:
         - exposedPort: 8080
     memoryLimit: "2048M"
