---
displayName: Java Maven
description: Java Stack with OpenJDK 8 and Maven 3.5.4
tags: ["Java", "OpenJDK", "Maven"]
icon: https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/master/ide/codeready-ide-stacks/src/main/resources/stacks-images/type-java.svg?sanitize=true
globalMemoryLimit: 2674Mi
