---
displayName: C/C++
description: C and C++ Developer Tools stack with GCC, cmake and make 
tags: ["tech-preview", "C", "C++", "clang", "GCC", "g++", "make", "cmake", "UBI8"]
icon: /images/type-cpp.svg
links:
  v2: https://github.com/crw-samples/c-plus-plus/tree/devfilev2
