---
displayName: C/C++
description: C and C++ Developer Tools stack with GCC 8.3.1, cmake 3.11.4 and make 4.2.1 
tags: ["tech-preview", "C", "C++", "clang", "GCC", "g++", "make", "cmake", "UBI8"]
icon: /images/type-cpp.svg
