---
displayName: Ansible
description: Development environment for Ansible playbook creation, testing with Molecule, and ansible-lint checks 
tags: ["Community", "Ansible", "Molecule"]
icon: /images/type-ansible.svg
links:
  v2: https://github.com/devspaces-samples/ansible-devspaces-demo/tree/devspaces-3.8-rhel-8
