---
displayName: Java 11 with JBoss EAP XP 3.0 Bootable Jar
description: Java stack with OpenJDK 11, Maven 3.6 and JBoss EAP XP 3.0 Bootable Jar
tags: ["Java", "OpenJDK", "Maven", "EAP", "Microprofile", "EAP XP", "Bootable Jar", "UBI8", "no-airgap-support"]
icon: /images/type-jboss.svg
links:
  v2: https://github.com/devspaces-samples/microprofile-quickstart-bootable/tree/devspaces-3-rhel-8
