# What's inside?

NOTE: the so-called master branch is deprecated and is no longer kept up to date.

For the latest release, see the crw-2.y-rhel-8 branch with the largest y value.

---

This repository hosts CodeReady Workspaces assembly that mainly inherits Eclipse Che artifacts and repackages some of them:

Differences as compared to upstream:

* Customized Dashboard (pics, icons, titles, loaders, links)
* Samples and Stacks modules
* Bayesian Language Server and agent
* Product Info plugin (IDE customizations: pics, titles links)
* Custom Dockerfile based on official RH OpenJDK image from RHCC

NOTE: Dockerfiles in this repo are NOT the ones used to build RHCC container images in OSBS.

## How to Build

### Pre-reqs

JDK 11
Maven 3.5+

### Build Assembly

Run the following command in the root of a repository:

```
mvn clean install
```

The build artifact used in the container image will be in `assembly/codeready-worksapces-assembly-main/target`


### How to Build Container Image Locally

First, build the CRW assembly in this repo:

```
mvn clean install
```

Then just use the `Dockerfile` in this repo to build:

```
podman build --force-rm -t registry.redhat.io/codeready-workspaces/server-rhel8:2.5 . && \
podman images | grep registry.redhat.io/codeready-workspaces/server-rhel8:2.5
```

You can then reference this image in your deployment (set image pull policy to *`Always`* to make sure it's pulled instead of the default one).

For more info on how to test locally built changes in a local OKD 3.11 (Minishift 1.34) cluster, see link:devdoc/building/building-crw.adoc#make-changes-to-crw-and-re-deploy-to-minishift[Build CodeReady Workspaces server container locally and deploy using Minishift].

[NOTE]
====

Once published, images will be in locations like these:

* registry.redhat.io/codeready-workspaces/configbump-rhel8
* registry.redhat.io/codeready-workspaces/crw-2-rhel8-operator
* registry.redhat.io/codeready-workspaces/crw-2-rhel8-operator-metadata
* registry.redhat.io/codeready-workspaces/devfileregistry-rhel8
* registry.redhat.io/codeready-workspaces/imagepuller-rhel8
* registry.redhat.io/codeready-workspaces/jwtproxy-rhel8
* registry.redhat.io/codeready-workspaces/machineexec-rhel8
* registry.redhat.io/codeready-workspaces/pluginbroker-artifacts-rhel8
* registry.redhat.io/codeready-workspaces/pluginbroker-metadata-rhel8
* registry.redhat.io/codeready-workspaces/plugin-java11-openj9-rhel8
* registry.redhat.io/codeready-workspaces/plugin-java11-rhel8
* registry.redhat.io/codeready-workspaces/plugin-java8-openj9-rhel8
* registry.redhat.io/codeready-workspaces/plugin-java8-rhel8
* registry.redhat.io/codeready-workspaces/plugin-kubernetes-rhel8
* registry.redhat.io/codeready-workspaces/plugin-openshift-rhel8
* registry.redhat.io/codeready-workspaces/pluginregistry-rhel8
* registry.redhat.io/codeready-workspaces/server-rhel8
* registry.redhat.io/codeready-workspaces/stacks-cpp-rhel8
* registry.redhat.io/codeready-workspaces/stacks-dotnet-rhel8
* registry.redhat.io/codeready-workspaces/stacks-golang-rhel8
* registry.redhat.io/codeready-workspaces/stacks-php-rhel8
* registry.redhat.io/codeready-workspaces/theia-endpoint-rhel8
* registry.redhat.io/codeready-workspaces/theia-rhel8
* registry.redhat.io/codeready-workspaces/traefik-rhel8
====

### How to Build Container Using Jenkins and OSBS/Brew (REQUIRES VPN)

If you have access to Red Hat VPN, clone the pkgs.devel repo, then run the `get-sources-jenkins.sh` script to pull the latest dependency tarball into the local project, and trigger a Brew build.

```
kinit
git clone ssh://kerberos-username@pkgs.devel.redhat.com/containers/codeready-workspaces
cd codeready-workspaces
./get-sources-jenkins.sh
```

See also:

* http://pkgs.devel.redhat.com/cgit/containers/codeready-workspaces/tree/README.adoc?h=crw-2.6-rhel-8

See this document for more on how to use those build systems, in order to publish a container image to Red Hat Container Catalog:

* https://github.com/redhat-developer/codeready-workspaces-productization/blob/master/devdoc/building/osbs-container-builds.adoc

### Keeping in sync with upstream

The Dockerfile and entrypoint.sh scripts in this repo are copied from link:http://pkgs.devel.redhat.com/cgit/containers/codeready-workspaces/tree/?h=crw-2.6-rhel-8[upstream repo] into this one using a link:https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Releng/job/crw_sync-pkgs.devel-to-github/[Jenkins job] which adjusts it so it will work locally.

Upstream: http://pkgs.devel.redhat.com/cgit/containers/codeready-workspaces/tree/?h=crw-2.6-rhel-8

Job: https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Releng/job/crw_sync-pkgs.devel-to-github/

Therefore any changes to files in this repo which also exist in upstream will be overwritten. Instead, push your changes into the pkgs.devel repo, and run the job to merge them into this one.

## Branding

To reskin this assembly, you need to edit the following files:

* link:assembly/codeready-workspaces-assembly-dashboard-war/src/main/webapp/assets/branding/branding-crw.css[assembly/codeready-workspaces-assembly-dashboard-war/src/main/webapp/assets/branding/branding-crw.css] - replacement for link:https://github.com/eclipse/che/blob/master/dashboard/src/assets/branding/branding.css[Che default css], copied via link:https://github.com/redhat-developer/codeready-workspaces/blob/master/Jenkinsfile#L177-L183[Jenkinsfile] during Pipeline build

* link:assembly/codeready-workspaces-assembly-dashboard-war/src/main/webapp/assets/branding/product.json.template[assembly/codeready-workspaces-assembly-dashboard-war/src/main/webapp/assets/branding/product.json.template]
** link:assembly/codeready-workspaces-assembly-dashboard-war/src/main/webapp/assets/branding/CodeReady.ico[assembly/codeready-workspaces-assembly-dashboard-war/src/main/webapp/assets/branding/CodeReady.ico] - browser tab favicon
** link:assembly/codeready-workspaces-assembly-dashboard-war/src/main/webapp/assets/branding/CRW_wordmark-bold-white.svg[assembly/codeready-workspaces-assembly-dashboard-war/src/main/webapp/assets/branding/CRW_wordmark-bold-white.svg] - top left wordmark
** link:assembly/codeready-workspaces-assembly-dashboard-war/src/main/webapp/assets/branding/CodeReady_icon_dashboard_footer.svg[assembly/codeready-workspaces-assembly-dashboard-war/src/main/webapp/assets/branding/CodeReady_icon_dashboard_footer.svg] - bottom left icon
** link:assembly/codeready-workspaces-assembly-dashboard-war/src/main/webapp/assets/branding/CodeReady_icon_loader.svg[assembly/codeready-workspaces-assembly-dashboard-war/src/main/webapp/assets/branding/CodeReady_icon_loader.svg] - dashboard loading animation

See also SVG assets in link:product/branding/[product/branding/] folder.

NOTE: When saving files in Inkscape, make sure you export as *Plain SVG*, then edit the resulting .svg file to remove any `<metadata>...</metadata>` tags and all their contents. You can also remove the `xmlns:rdf` definition. This will ensure they compile correctly.

![.github/workflows/gh_actions_pr.yaml](https://github.com/redhat-developer/codeready-workspaces/workflows/.github/workflows/gh_actions_pr.yaml/badge.svg?event=pull_request)