# What's inside?

NOTE: the so-called master branch is deprecated and is no longer kept up to date. Instead, the latest nightly sources are in **crw-2-rhel-8 branch**, synced to upstream projects' main (or master) branches.

For the latest stable release, see the **crw-2.y-rhel-8** branch with the largest y value.

---

This repository hosts CodeReady Workspaces assembly that mainly inherits Eclipse Che artifacts and repackages some of them:

Differences as compared to upstream:

* Customized Dashboard (pics, icons, titles, loaders, links)
* Samples and Stacks modules
* Bayesian Language Server and agent
* Product Info plugin (IDE customizations: pics, titles links)
* Custom Dockerfile based on official RH OpenJDK image from RHCC

NOTE: Dockerfiles in this repo are NOT the ones used to build RHCC container images in OSBS.

## How to Build

### Pre-reqs

JDK 11
Maven 3.5+

### Build Assembly

Run the following command in the root of a repository:

```
mvn clean install
```

The build artifact used in the container image will be in `assembly/codeready-worksapces-assembly-main/target`


### How to Build Container Image Locally

First, build the CRW assembly in this repo:

```
mvn clean install
```

Then just use the `Dockerfile` in this repo to build:

```
podman build --force-rm -t registry.redhat.io/codeready-workspaces/server-rhel8:2.y . && \
podman images | grep registry.redhat.io/codeready-workspaces/server-rhel8:2.y
```

You can then reference this image in your deployment (set image pull policy to *`Always`* to make sure it's pulled instead of the default one).

For more info on how to test locally built changes in a local OKD 3.11 (Minishift 1.34) cluster, see link:devdoc/building/building-crw.adoc#make-changes-to-crw-and-re-deploy-to-minishift[Build CodeReady Workspaces server container locally and deploy using Minishift].

[NOTE]
====

Once published, images will be in locations like these:

* registry.redhat.io/codeready-workspaces/configbump-rhel8
* registry.redhat.io/codeready-workspaces/crw-2-rhel8-operator
* registry.redhat.io/codeready-workspaces/crw-2-rhel8-operator-metadata
* registry.redhat.io/codeready-workspaces/devfileregistry-rhel8
* registry.redhat.io/codeready-workspaces/imagepuller-rhel8
* registry.redhat.io/codeready-workspaces/jwtproxy-rhel8
* registry.redhat.io/codeready-workspaces/machineexec-rhel8
* registry.redhat.io/codeready-workspaces/pluginbroker-artifacts-rhel8
* registry.redhat.io/codeready-workspaces/pluginbroker-metadata-rhel8
* registry.redhat.io/codeready-workspaces/plugin-java11-openj9-rhel8
* registry.redhat.io/codeready-workspaces/plugin-java11-rhel8
* registry.redhat.io/codeready-workspaces/plugin-java8-openj9-rhel8
* registry.redhat.io/codeready-workspaces/plugin-java8-rhel8
* registry.redhat.io/codeready-workspaces/plugin-kubernetes-rhel8
* registry.redhat.io/codeready-workspaces/plugin-openshift-rhel8
* registry.redhat.io/codeready-workspaces/pluginregistry-rhel8
* registry.redhat.io/codeready-workspaces/server-rhel8
* registry.redhat.io/codeready-workspaces/stacks-cpp-rhel8
* registry.redhat.io/codeready-workspaces/stacks-dotnet-rhel8
* registry.redhat.io/codeready-workspaces/stacks-golang-rhel8
* registry.redhat.io/codeready-workspaces/stacks-php-rhel8
* registry.redhat.io/codeready-workspaces/theia-endpoint-rhel8
* registry.redhat.io/codeready-workspaces/theia-rhel8
* registry.redhat.io/codeready-workspaces/traefik-rhel8
====

### How to Build CRW Server Container Using casc Jenkins (REQUIRES VPN)

See this document for how to use those build systems, in order to publish a container image to Red Hat Container Catalog:

* https://github.com/redhat-developer/codeready-workspaces-productization/blob/master/devdoc/building/osbs-container-builds.adoc

See also:

* https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/CRW_CI/ (crw-server_*)
* https://github.com/redhat-developer/codeready-workspaces-images#jenkins-jobs

### How to Build CRW Server Container Locally (REQUIRES VPN)

If you have access to Red Hat VPN, clone the pkgs.devel repo, then run the `get-sources-jenkins.sh` script to pull the latest dependency tarball into the local project, and trigger a Brew build.

```
kinit
git clone ssh://kerberos-username@pkgs.devel.redhat.com/containers/codeready-workspaces
cd codeready-workspaces
./get-sources-jenkins.sh
```

### Keeping CRW Server in sync with upstream and downstream

Upstream: https://github.com/eclipse/che
Midstream: (this repo)
Downstream: http://pkgs.devel.redhat.com/cgit/containers/codeready-workspaces/tree/?h=crw-2-rhel-8

Sync jobs:

* https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/CRW_CI/ (crw-server_*)
* https://gitlab.cee.redhat.com/codeready-workspaces/crw-jenkins/-/tree/master/jobs/CRW_CI (sources)
* https://github.com/redhat-developer/codeready-workspaces-images#jenkins-jobs (copied sources)

The Jenkinsfile in this repo has moved. See:

* https://gitlab.cee.redhat.com/codeready-workspaces/crw-jenkins/-/tree/master/jobs/CRW_CI
* https://github.com/redhat-developer/codeready-workspaces-images#jenkins-jobs


### Keeping CRW dependencies in sync with upstream and downstream

Folders under link:dependencies[/dependencies] are synced to https://github.com/redhat-developer/codeready-workspaces-images. If no matching project exists under the link:dependencies[/dependencies] folder, sync occurs directly from an upstream Che project.

Sync jobs:

* https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/CRW_CI/ (jobs)
* https://gitlab.cee.redhat.com/codeready-workspaces/crw-jenkins/-/tree/master/jobs/CRW_CI (sources)
* https://github.com/redhat-developer/codeready-workspaces-images#jenkins-jobs (copied sources)

These files have moved, as they sync directly from an upstream repo:

    * dependencies/che-jwtproxy/Jenkinsfile
    * dependencies/che-machine-exec/Jenkinsfile
    * dependencies/che-pluginbroker/Jenkinsfile
    * dependencies/configbump/Jenkinsfile
    * dependencies/kubernetes-image-puller/Jenkinsfile
    * dependencies/push-latest.Jenkinsfile
    * dependencies/send-email-qe-build-list.Jenkinsfile
    * dependencies/traefik/Jenkinsfile
    * dependencies/update-digests.Jenkinsfile


## Branding

Branding is currently in two places.

### Dashboard

To reskin the Che server assembly, you need to edit the following files, which are used in the link:https://github.com/eclipse/che-dashboard/tree/master/assets/branding[Che Dashboard]:

* link:assembly/branding/branding-crw.css[assembly/branding/branding-crw.css] - replacement for link:https://github.com/eclipse/che-dashboard/tree/master/assets/branding/branding.css[Che default css], copied via link:https://github.com/redhat-developer/codeready-workspaces-images/blob/crw-2-rhel-8/crw-jenkins/jobs/CRW_CI/crw-server_2.x.jenkinsfile[Jenkinsfile] during Pipeline build

* link:assembly/branding/product.json.template[assembly/branding/product.json.template]
** link:assembly/branding/favicon.ico[assembly/branding/favicon.ico] - browser tab favicon
** link:assembly/branding/che-logo-text.svg[assembly/branding/che-logo-text.svg] - top left wordmark
** link:assembly/branding/che-logo.svg[assembly/branding/che-logo.svg] - bottom left icon
** link:assembly/branding/loader.svg[assembly/branding/loader.svg] - dashboard loading animation

See also SVG assets in link:product/branding/[product/branding/] folder.

NOTE: In a future release, the Che Dashboard will be a separate deployment from the Che Server, which means the above information may become incorrect.

### Theia

In addition to the Che Dashboard branding, there is also branding elements for link:https://github.com/eclipse-che/che-theia[Che Theia]. See details in link:https://github.com/redhat-developer/codeready-workspaces-theia/tree/crw-2-rhel-8/conf/theia/branding[codeready-workspaces-theia/conf/theia/branding]. 

### A note about SVG files 

If using Inkscape to save files, make sure you export as *Plain SVG*, then edit the resulting .svg file to remove any `<metadata>...</metadata>` tags and all their contents. You can also remove the `xmlns:rdf` definition. This will ensure they compile correctly.

