---
displayName: "PHP CakePHP"
description: PHP Stack with PHP, Apache Web Server, Composer and a quickstart CakePHP application for OpenShift
tags: ["Tech-Preview", "PHP", "CakePHP", "Apache", "Composer", "UBI8"]
icon: /images/type-php.svg
links:
  v2: https://github.com/devspaces-samples/cakephp-ex/tree/devspaces-3-rhel-8
