---
displayName: Java with JBoss EAP 7.4
description: Java stack with OpenJDK 11, Maven 3.6 and JBoss EAP 7.4
tags: ["Java", "OpenJDK", "Maven", "EAP", "RHEL8"]
icon: /images/type-jboss.svg
links:
  v2: https://github.com/devspaces-samples/jboss-eap-quickstarts/tree/devspaces-3-rhel-8
