---
displayName: "PHP-DI"
description: PHP Stack with PHP 7.3.5, Apache Web Server 2.4.37 and Composer 1.8.4
tags: ["PHP", "Apache", "Composer", "UBI8"]
icon: /images/type-php.svg
globalMemoryLimit: 2430Mi
