---
displayName: Java with JBoss EAP 7.4
description: Java stack with OpenJDK 8, Maven 3.6 and JBoss EAP 7.4
tags: ["Java", "OpenJDK", "Maven", "EAP", "RHEL7"]
icon: /images/type-jboss.svg
links:
  v2: https://github.com/crw-samples/jboss-eap-quickstarts/tree/devspaces-3.0-rhel-8
