---
displayName: "PHP"
description: PHP Stack with PHP 
tags: ["Tech-Preview", "PHP", "UBI8"]
icon: /images/type-php.svg
links:
  v2: https://github.com/devspaces-samples/php-hello-world/tree/devspaces-3.16-rhel-8
