---
displayName: "PHP-DI"
description: PHP Stack with PHP, Apache Web Server and Composer
tags: ["Tech-Preview", "PHP", "Apache", "Composer", "UBI8"]
icon: /images/type-php.svg
links:
  v2: https://github.com/devspaces-samples/demo/tree/devspaces-3-rhel-8
