#!/usr/bin/env groovy

// PARAMETERS for this pipeline:
// def FORCE_BUILD = "false"
// def SOURCE_BRANCH = "crw-2.1" // ref/tags/v0.24.0, or crw-2.1, or master :: branch of source repo from which to find and sync commits to pkgs.devel repo

def SOURCE_REPO = "eclipse/che-plugin-broker" //source repo from which to find and sync commits to pkgs.devel repo 
def GIT_PATH1 = "containers/codeready-workspaces-pluginbroker-metadata" // dist-git repo to use as target
def GIT_PATH2 = "containers/codeready-workspaces-pluginbroker-artifacts" // dist-git repo to use as target

def GIT_BRANCH = "crw-2.2-rhel-8" // target branch in dist-git repo, eg., crw-2.2-rhel-8
def SCRATCH = "false"
def PUSH_TO_QUAY = "true"
def QUAY_PROJECT1 = "pluginbroker-metadata" // also used for the Brew dockerfile params
def QUAY_PROJECT2 = "pluginbroker-artifacts" // also used for the Brew dockerfile params

def OLD_SHA1=""
def OLD_SHA2=""
def SRC_SHA1=""

def buildNode = "rhel7-releng" // slave label
timeout(120) {
	node("${buildNode}"){ stage "Sync repos"
    wrap([$class: 'TimestamperBuildWrapper']) {
		  cleanWs()
      withCredentials([string(credentialsId:'devstudio-release.token', variable: 'GITHUB_TOKEN'), 
        file(credentialsId: 'crw-build.keytab', variable: 'CRW_KEYTAB')]) {
      checkout([$class: 'GitSCM', 
        branches: [[name: "${SOURCE_BRANCH}"]], 
        doGenerateSubmoduleConfigurations: false,
        credentialsId: 'devstudio-release',
        poll: true,
        extensions: [
          [$class: 'RelativeTargetDirectory', relativeTargetDir: "sources"],
          [$class: 'PathRestriction', excludedRegions: '', includedRegions: 'dependencies/che-pluginbroker/.*'],
          [$class: 'DisableRemotePoll']
        ],
        submoduleCfg: [], 
        userRemoteConfigs: [[url: "https://github.com/${SOURCE_REPO}.git"]]])

  	 	def BOOTSTRAP = '''#!/bin/bash -xe

# bootstrapping: if keytab is lost, upload to 
# https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/credentials/store/system/domain/_/
# then set Use secret text above and set Bindings > Variable (path to the file) as ''' + CRW_KEYTAB + '''
chmod 700 ''' + CRW_KEYTAB + ''' && chown ''' + USER + ''' ''' + CRW_KEYTAB + '''
# create .k5login file
echo "crw-build/codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com@REDHAT.COM" > ~/.k5login
chmod 644 ~/.k5login && chown ''' + USER + ''' ~/.k5login
 echo "pkgs.devel.redhat.com,10.19.208.80 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAplqWKs26qsoaTxvWn3DFcdbiBxqRLhFngGiMYhbudnAj4li9/VwAJqLm1M6YfjOoJrj9dlmuXhNzkSzvyoQODaRgsjCG5FaRjuN8CSM/y+glgCYsWX1HFZSnAasLDuW0ifNLPR2RBkmWx61QKq+TxFDjASBbBywtupJcCsA5ktkjLILS+1eWndPJeSUJiOtzhoN8KIigkYveHSetnxauxv1abqwQTk5PmxRgRt20kZEFSRqZOJUlcl85sZYzNC/G7mneptJtHlcNrPgImuOdus5CW+7W49Z/1xqqWI/iRjwipgEMGusPMlSzdxDX4JzIx6R53pDpAwSAQVGDz4F9eQ==
" >> ~/.ssh/known_hosts

ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

# see https://mojo.redhat.com/docs/DOC-1071739
if [[ -f ~/.ssh/config ]]; then mv -f ~/.ssh/config{,.BAK}; fi
echo "
GSSAPIAuthentication yes
GSSAPIDelegateCredentials yes

Host pkgs.devel.redhat.com
User crw-build/codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com@REDHAT.COM
" > ~/.ssh/config
chmod 600 ~/.ssh/config

# initialize kerberos
export KRB5CCNAME=/var/tmp/crw-build_ccache
kinit "crw-build/codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com@REDHAT.COM" -kt ''' + CRW_KEYTAB + '''
klist # verify working

hasChanged=0

# REQUIRE: skopeo
curl -L -s -S https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/master/product/updateBaseImages.sh -o /tmp/updateBaseImages.sh
chmod +x /tmp/updateBaseImages.sh 
cd ${WORKSPACE}/sources
  git checkout --track origin/''' + SOURCE_BRANCH + ''' || true
  export GITHUB_TOKEN=''' + GITHUB_TOKEN + ''' # echo "''' + GITHUB_TOKEN + '''"
  git config user.email "nickboldt+devstudio-release@gmail.com"
  git config user.name "Red Hat Devstudio Release Bot"
  git config --global push.default matching
  OLD_SHA=\$(git rev-parse HEAD) # echo ${OLD_SHA:0:8}

  # TODO enable generating PRs for upstream rhel.Dockerfile
  # /tmp/updateBaseImages.sh -b ''' + SOURCE_BRANCH + ''' -w ${WORKSPACE}/sources/build/metadata -f rhel.Dockerfile
  # /tmp/updateBaseImages.sh -b ''' + SOURCE_BRANCH + ''' -w ${WORKSPACE}/sources/build/artifacts -f rhel.Dockerfile
  # NEW_SHA=$(git rev-parse HEAD) # echo ${NEW_SHA:0:8}
  # if [[ "${OLD_SHA}" != "${NEW_SHA}" ]]; then hasChanged=1; fi
cd ..
for targetN in target1 target2; do
    # fetch sources to be updated
    if [[ \$targetN == "target1" ]]; then GIT_PATH="''' + GIT_PATH1 + '''"; else GIT_PATH="''' + GIT_PATH2 + '''"; fi
    if [[ ! -d ${WORKSPACE}/${targetN} ]]; then git clone ssh://crw-build@pkgs.devel.redhat.com/${GIT_PATH} ${targetN}; fi
    cd ${WORKSPACE}/${targetN}
    git checkout --track origin/''' + GIT_BRANCH + ''' || true
    git config user.email crw-build@REDHAT.COM
    git config user.name "CRW Build"
    git config --global push.default matching
    cd ..
done
'''
      sh BOOTSTRAP

      SRC_SHA1 = sh(script: '''#!/bin/bash -xe
      cd ${WORKSPACE}/sources; git rev-parse HEAD
      ''', returnStdout: true)
      println "Got SRC_SHA1 in sources folder: " + SRC_SHA1

      OLD_SHA1 = sh(script: '''#!/bin/bash -xe
      cd ${WORKSPACE}/target1; git rev-parse HEAD
      ''', returnStdout: true)
      println "Got OLD_SHA1 in target1 folder: " + OLD_SHA1

      OLD_SHA2 = sh(script: '''#!/bin/bash -xe
      cd ${WORKSPACE}/target2; git rev-parse HEAD
      ''', returnStdout: true)
      println "Got OLD_SHA2 in target2 folder: " + OLD_SHA2

  	 	sh BOOTSTRAP + '''
for targetN in target1 target2; do
    # rsync files in github to dist-git
    SYNC_FILES="brokers build cfg common CONTRIBUTING.md  devfile.yaml  Gopkg.lock  Gopkg.toml  LICENSE  Makefile  model  README.md  storage  utils  vendor VERSION"
    for d in ${SYNC_FILES}; do
    if [[ -f ${WORKSPACE}/sources/${d} ]]; then 
        rsync -zrlt ${WORKSPACE}/sources/${d} ${WORKSPACE}/${targetN}/${d}
    elif [[ -d ${WORKSPACE}/sources/${d} ]]; then
        # copy over the files 
        rsync -zrlt ${WORKSPACE}/sources/${d}/* ${WORKSPACE}/${targetN}/${d}/
        # sync the directory and delete from target if deleted from source 
        rsync -zrlt --delete ${WORKSPACE}/sources/${d}/ ${WORKSPACE}/${targetN}/${d}/ 
    fi
    done

    # apply changes from upstream che-pluginbroker/build/*/rhel.Dockerfile to downstream Dockerfile
    SOURCEDOCKERFILE=""
    TARGETDOCKERFILE=""
    if [[ \$targetN == "target1" ]]; then 
      SOURCEDOCKERFILE="${WORKSPACE}/sources/build/metadata/rhel.Dockerfile"
      TARGETDOCKERFILE="${WORKSPACE}/target1/Dockerfile"
      QUAY_PROJECT="''' + QUAY_PROJECT1 + '''"
    elif [[ \$targetN == "target2" ]]; then 
      SOURCEDOCKERFILE="${WORKSPACE}/sources/build/artifacts/rhel.Dockerfile"
      TARGETDOCKERFILE="${WORKSPACE}/target2/Dockerfile"
      QUAY_PROJECT="''' + QUAY_PROJECT2 + '''"
    fi

    # TODO should this be a branch instead of just master?
    CRW_VERSION=`wget -qO- https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/master/dependencies/VERSION`
    #apply patches
    if [[ ${SOURCEDOCKERFILE} != "" ]] && [[ ${TARGETDOCKERFILE} != "" ]]; then
      sed ${SOURCEDOCKERFILE} \
        -e "s#FROM registry.redhat.io/#FROM #g" \
        -e "s#FROM registry.access.redhat.com/#FROM #g" \
        > ${TARGETDOCKERFILE}
    fi

    METADATA='ENV SUMMARY="Red Hat CodeReady Workspaces '${QUAY_PROJECT}' container" \\\r
        DESCRIPTION="Red Hat CodeReady Workspaces '${QUAY_PROJECT}' container" \\\r
        PRODNAME="codeready-workspaces" \\\r
        COMPNAME="'${QUAY_PROJECT}'-rhel8" \r
    LABEL summary="$SUMMARY" \\\r
          description="$DESCRIPTION" \\\r
          io.k8s.description="$DESCRIPTION" \\\r
          io.k8s.display-name=\"$DESCRIPTION" \\\r
          io.openshift.tags="$PRODNAME,$COMPNAME" \\\r
          com.redhat.component="$PRODNAME-$COMPNAME-container" \\\r
          name="$PRODNAME/$COMPNAME" \\\r
          version="'${CRW_VERSION}'" \\\r
          license="EPLv2" \\\r
          maintainer="Nick Boldt <nboldt@redhat.com>" \\\r
          io.openshift.expose-services="" \\\r
          usage="" \r'

    echo -e "$METADATA" >> ${TARGETDOCKERFILE}

    # push changes in github to dist-git
    cd ${WORKSPACE}/${targetN}
    if [[ \$(git diff --name-only) ]]; then # file changed
    OLD_SHA=\$(git rev-parse HEAD) # echo ${OLD_SHA:0:8}
    git add Dockerfile ${SYNC_FILES}
    git commit -s -m "[sync] Update from ''' + SOURCE_REPO + ''' @ ${SRC_SHA1:0:8}" Dockerfile ${SYNC_FILES}
    git push origin ''' + GIT_BRANCH + '''
    NEW_SHA=\$(git rev-parse HEAD) # echo ${NEW_SHA:0:8}
    if [[ "${OLD_SHA}" != "${NEW_SHA}" ]]; then hasChanged=1; fi
    echo "[sync] Updated pkgs.devel @ ${NEW_SHA:0:8} from ''' + SOURCE_REPO + ''' @ ${SRC_SHA1:0:8}"
    fi
    cd ..

    # update base image
    cd ${WORKSPACE}/${targetN}
    OLD_SHA=\$(git rev-parse HEAD) # echo ${OLD_SHA:0:8}
    /tmp/updateBaseImages.sh -b ''' + GIT_BRANCH + ''' -w ${TARGETDOCKERFILE%/*} -f ${TARGETDOCKERFILE##*/}
    NEW_SHA=\$(git rev-parse HEAD) # echo ${NEW_SHA:0:8}
    if [[ "${OLD_SHA}" != "${NEW_SHA}" ]]; then hasChanged=1; fi
    cd ..
done

if [[ ''' + FORCE_BUILD + ''' == "true" ]]; then hasChanged=1; fi

if [[ ${hasChanged} -eq 1 ]]; then
  for QRP in pluginbroker-metadata pluginbroker-artifacts; do
    QUAY_REPO_PATH=""; if [[ ''' + PUSH_TO_QUAY + ''' == "true" ]]; then QUAY_REPO_PATH="${QRP}-rhel8"; fi
    curl \
"https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/get-sources-rhpkg-container-build/buildWithParameters?\
token=CI_BUILD&\
cause=${QUAY_REPO_PATH}+respin+by+${BUILD_TAG}&\
GIT_BRANCH=''' + GIT_BRANCH + '''&\
GIT_PATHs=containers/codeready-workspaces-${QRP}&\
QUAY_REPO_PATHs=${QUAY_REPO_PATH}&\
JOB_BRANCH=master&\
FORCE_BUILD=true&\
SCRATCH=''' + SCRATCH + '''"
  done
fi

if [[ ${hasChanged} -eq 0 ]]; then
  echo "No changes upstream, nothing to commit"
fi
		  '''
    }

        def NEW_SHA1 = sh(script: '''#!/bin/bash -xe
        cd ${WORKSPACE}/target1; git rev-parse HEAD
        ''', returnStdout: true)
        println "Got NEW_SHA1 in target1 folder: " + NEW_SHA1

        def NEW_SHA2 = sh(script: '''#!/bin/bash -xe
        cd ${WORKSPACE}/target2; git rev-parse HEAD
        ''', returnStdout: true)
        println "Got NEW_SHA2 in target2 folder: " + NEW_SHA2

      if (NEW_SHA1.equals(OLD_SHA1) && NEW_SHA2.equals(OLD_SHA2) && !FORCE_BUILD.equals("true")) {
        currentBuild.result='UNSTABLE'
      }
    }
	}
}
