---
displayName: IntelliJ IDEA Community Edition
description: IntelliJ IDEA Community Edition based editor stack
tags: ["Tech-Preview", "JetBrains", "Java", "RHEL8", "IntelliJ", "IDEA"]
icon: /images/type-intellij.svg
