---
displayName: IntelliJ IDEA Community Edition
description: IntelliJ IDEA Community Edition based editor stack
tags: ["Tech-Preview", "JetBrains", "Java", "RHEL8", "IntelliJ", "IDEA"]
icon: /images/type-intellij.svg
links:
  v2: https://github.com/devspaces-samples/gradle-demo-project/tree/devspaces-3-rhel-8
