---
displayName: C/C++
description: C and C++ Developer Tools stack with GCC, cmake and make 
tags: ["Tech-Preview", "C", "C++", "Clang", "GCC", "g++", "make", "cmake", "UBI8"]
icon: /images/type-cpp.svg
links:
  v2: https://github.com/devspaces-samples/c-plus-plus/tree/devspaces-3.13-rhel-8
