#!/usr/bin/env groovy
import groovy.transform.Field

// PARAMETERS for this pipeline:
//   FORCE_BUILD

@Field String SOURCE_BRANCH = "master"
def String SOURCE_REPO = "che-incubator/configbump" // source repo from which to find commits
def SYNC_REPO="configbump"


def DWNSTM_REPO = "redhat-developer/codeready-workspaces"
def MIDSTM_BRANCH = "crw-2.5-rhel-8" // target branch in dist-git repo, eg., crw-2.5-rhel-8
def DWNSTM_BRANCH = MIDSTM_BRANCH

// Nodes to run artifact build on ex. ['rhel7-releng', 's390x-rhel7-beaker', 'ppc64le-rhel7-beaker']
// TODO enable Z and P
def List build_nodes = ['rhel7-releng'] //, 's390x-rhel7-beaker', 'ppc64le-rhel7-beaker']
def Map tasks = [failFast: false]

@Field String QUAY_REPO_PATH = ""
def OLD_SHA=""
def NEW_SHA=""
def SOURCE_SHA=""
for (int i=0; i < build_nodes.size(); i++) {
  def String nodeLabel = "${build_nodes[i]}"
  tasks[build_nodes[i]] = { ->

    timeout(120) {
        node(nodeLabel){ 
            stage("Sync repos + build artifacts") {
                wrap([$class: 'TimestamperBuildWrapper']) {
                    sh('curl -sSLO https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/crw-2.5-rhel-8/product/util.groovy')
                    def util = load "${WORKSPACE}/util.groovy"
                    cleanWs()
                    CRW_VERSION = util.getCrwVersion(DWNSTM_BRANCH)
                    println "CRW_VERSION = '" + CRW_VERSION + "'"
                    util.installSkopeo(CRW_VERSION)
                    QUAY_REPO_PATH=util.getCRWShortName(SYNC_REPO) + "-rhel8"

                    withCredentials([string(credentialsId:'devstudio-release.token', variable: 'GITHUB_TOKEN'),
                        file(credentialsId: 'crw-build.keytab', variable: 'CRW_KEYTAB')]) {
                        util.bootstrap(CRW_KEYTAB)
                        println "########################################################################################################"
                        println "##  Clone and update github.com/${SOURCE_REPO}.git"
                        println "########################################################################################################"
                        util.cloneRepo("https://github.com/${SOURCE_REPO}.git", "${WORKSPACE}/sources/${SYNC_REPO}", SOURCE_BRANCH)
                        // util.updateBaseImages("${WORKSPACE}/sources/${SYNC_REPO}", SOURCE_BRANCH)
                        SOURCE_SHA = util.getLastCommitSHA("${WORKSPACE}/sources/${SYNC_REPO}")
                        println "Got SOURCE_SHA in sources folder: " + SOURCE_SHA

                        
                        println "########################################################################################################"
                        println "##  Sync ${SYNC_REPO} to pkgs.devel"
                        println "########################################################################################################"
                        util.cloneRepo("ssh://crw-build@pkgs.devel.redhat.com/containers/codeready-workspaces-${SYNC_REPO}", "${WORKSPACE}/targetdwn/${SYNC_REPO}", DWNSTM_BRANCH)

                        sh('''rsync -avhz --checksum --delete --exclude .git/ ${WORKSPACE}/sources/''' + SYNC_REPO + '''/ ${WORKSPACE}/targetdwn/''' + SYNC_REPO)

                        OLD_SHA = util.getLastCommitSHA("${WORKSPACE}/targetdwn/${SYNC_REPO}")
                        println "Got OLD_SHA in targetdwn/${SYNC_REPO} folder: " + OLD_SHA

                        // build project in Jenkins so we can collect asset-* files later via get-sources-jenkins.sh, then trigger a build brew with those files
                        if (NEW_SHA != OLD_SHA || FORCE_BUILD == "true") {
                            sh('''#!/bin/bash -xe
                                cd ${WORKSPACE}/targetdwn/''' + SYNC_REPO + ''' && chmod +x ./build/dockerfiles/*.sh && ./build/dockerfiles/rhel.Dockerfile.extract.assets.sh
                            ''')
                            archiveArtifacts fingerprint: true, onlyIfSuccessful: true, allowEmptyArchive: false, artifacts: "asset-configbump-*.tar.gz, logs/*"
                        } else {
                            println "No changes upstream, nothing to commit"
                        }

                        // TODO append brew metadata to brew.Dockerfile in downstream

                        // push to dist-git
                        sh('''#!/bin/bash -xe
                        cd ${WORKSPACE}/targetdwn/''' + SYNC_REPO + '''
                        if [[ \$(git diff --name-only) ]]; then # file changed
                            export KRB5CCNAME=/var/tmp/crw-build_ccache
                            git add .
                            git commit -s -m "[sync] Update from ''' + SOURCE_REPO + ''' @ ''' + SOURCE_SHA[0..7] + '''"
                            git push origin ''' + DWNSTM_BRANCH + ''' || true
                        fi''')

                        // run get-sources-jenkins to ensure we have the latest sources (in case we clobbered a previous run) and update source repo
                        // sh('''#!/bin/bash -xe
                        // export KRB5CCNAME=/var/tmp/crw-build_ccache
                        // cd ${WORKSPACE}/targetdwn/''' + SYNC_REPO + '''
                        // ./get-sources-jenkins.sh -n ''' + CRW_VERSION + '''
                        // COMMIT_SHA="$(git log origin/crw-2.5-rhel-8..crw-2.5-rhel-8 --pretty=format:%H)"
                        // COMMIT_MSG="$(git log origin/crw-2.5-rhel-8..crw-2.5-rhel-8 --pretty=format:%B)"
                        // if [ ! -z "$COMMIT_SHA" ] ; then
                        //     for f in $(git diff-tree --no-commit-id --name-only -r "$COMMIT_SHA") ; do
                        //     cp $f ${WORKSPACE}/sources/''' + SYNC_REPO + '''
                        //     done
                        //     git push origin ''' + DWNSTM_BRANCH + ''' || true

                        //     # update source repo with updates from running get-sources-jenkins
                        //     cd ${WORKSPACE}/sources/''' + SYNC_REPO + '''
                        //     git commit -am "$COMMIT_MSG" || true
                        //     git push origin ''' + SOURCE_BRANCH + ''' || true
                        // fi
                        // ''')

                        NEW_SHA = util.getLastCommitSHA("${WORKSPACE}/targetdwn/${SYNC_REPO}")
                        println "Got NEW_SHA in targetdwn/${SYNC_REPO} folder: " + NEW_SHA

                    } // withCredentials
                } // wrap
            } // stage
        } // node
    } // timeout
  } // tasks
} // for


stage("Builds") {
    parallel(tasks)
}

// kick off get-sources-rhpkg-container-build job
def String nodeLabel = "${build_nodes[0]}"
node(nodeLabel) {
  stage ("Build containers on ${nodeLabel}") {
    echo "currentBuild.result = " + currentBuild.result
    if (!currentBuild.result.equals("ABORTED") && !currentBuild.result.equals("FAILED")) {
      CRW_VERSION = util.getCrwVersion(MIDSTM_BRANCH)
      println "CRW_VERSION = '" + CRW_VERSION + "'"
      build(
            job: 'get-sources-rhpkg-container-build',
            wait: false,
            propagate: false,
            parameters: [
              [
                $class: 'StringParameterValue',
                name: 'token',
                value: "CI_BUILD"
              ],
              [
                $class: 'StringParameterValue',
                name: 'cause',
                value: "configbump+respin+by+${BUILD_TAG}"
              ],
              [
                $class: 'StringParameterValue',
                name: 'GIT_BRANCH',
                value: "${DWNSTM_BRANCH}"
              ],
              [
                $class: 'StringParameterValue',
                name: 'GIT_PATHs',
                value: "containers/codeready-workspaces-configbump"
              ],
              [
                $class: 'StringParameterValue',
                name: 'QUAY_REPO_PATHs',
                value: "${QUAY_REPO_PATH}"
              ],
              [
                $class: 'StringParameterValue',
                name: 'JOB_BRANCH',
                value: "${CRW_VERSION}"
              ],
              [
                $class: 'StringParameterValue',
                name: 'FORCE_BUILD',
                value: "true"
              ],
              [
                $class: 'StringParameterValue',
                name: 'SCRATCH',
                value: "${SCRATCH}"
              ]
            ]
          )
    } // if
  } // stage
} //node
