---
displayName: Node.js Express
description: Node.js stack with NPM 8, Node.js 16 and Express Web Application
tags: ["Node.js", "NPM", "Express", "UBI8"]
icon: /images/type-node.svg
links:
  v2: https://github.com/devspaces-samples/web-nodejs-sample/tree/devspaces-3.8-rhel-8
