== Build che-theia theia image

To run this build locally using RHEL dependencies:

```
./build.sh --dockerfile:rhel.Dockerfile
```

== Build che-theia theia image for use in Brew

To run this build in order to collect dependencies needed to run in Brew:

```
# prepare
sudo rm -f root-local.tgz /tmp/root-local/

# run build
CONTAINERNAME="quay.io/crw/theia-rhel8:2.0"
./build.sh --offline --dockerfile:rhel.Dockerfile --image-name:"${CONTAINERNAME}"

# collect node_modules from the container
mkdir -p /tmp/root-local/ && sudo chmod 777 /tmp/root-local && sudo chown -R 1002:1002 /tmp/root-local
docker run -it --entrypoint /bin/bash -v /tmp/root-local/:/tmp/root-local/ ${CONTAINERNAME} -c "collect.installed.dependencies.sh"

# build tarball & put in build folder
pushd /tmp/root-local >/dev/null && sudo tar -pczf /tmp/root-local.tgz ./* && popd >/dev/null && sudo mv -f /tmp/root-local.tgz .

# cleanup
sudo rm -fr /tmp/root-local/
```

Now you can copy `root-local.tgz` to the root of your Brew build folder.

You may also want to update your Brew build's Dockerfile from the contents in the generated .Dockerfile.

Note that the `theia` build depends on the creation and publication of the `theia-dev` image, which is currently being published here:

* registry-proxy.engineering.redhat.com/rh-osbs/codeready-workspaces-theia-dev-rhel8:2.0 and
* link:https://quay.io/repository/crw/theia-dev-rhel8?tag=2.0&tab=tags[quay.io/crw/theia-dev-rhel8:2.0]


If building link:../[`theia-dev`] locally, you can override the base image in link:rhel.Dockerfile[`rhel.Dockerfile`] to use your locally built version.

