#!/usr/bin/env groovy

// PARAMETERS for this pipeline:
// branchToBuildCRW = codeready-workspaces branch to build: */2.0.x or */master
// branchToBuildCheTheia = che-theia branch to build: refs/tags/7.0.0, */7.1.x, or */master
// che_theia_version = master
// che_theia_tag = next
// che_theia_branch = master
// che_theia_gitref = refs/heads/master
// node == slave label, eg., rhel7-devstudio-releng-16gb-ram||rhel7-16gb-ram||rhel7-devstudio-releng||rhel7 or rhel7-32gb||rhel7-16gb||rhel7-8gb
// GITHUB_TOKEN = (github token)

def installNPM(){
	def nodeHome = tool 'nodejs-10.15.3'
	env.PATH="${nodeHome}/bin:${env.PATH}"

	sh '''#!/bin/bash -xe

echo '
registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/
cafile=/etc/pki/ca-trust/source/anchors/RH-IT-Root-CA.crt
strict-ssl=false
virtual/:_authToken=credentials
always-auth=true
' > ${HOME}/.npmrc

echo '
# registry "https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/"
registry "https://registry.yarnpkg.com"
cafile /etc/pki/ca-trust/source/anchors/RH-IT-Root-CA.crt
strict-ssl false
' > ${HOME}/.yarnrc

cat ${HOME}/.npmrc
cat ${HOME}/.yarnrc

npm install --global yarn
npm config get; yarn config get list
npm --version; yarn --version
'''
}

timeout(120) {
	node("${node}"){ stage "Build Theia"
		cleanWs()
		// for private repo, use checkout(credentialsId: 'devstudio-release')
		checkout([$class: 'GitSCM', 
			branches: [[name: "${branchToBuildCRW}"]], 
			doGenerateSubmoduleConfigurations: false, 
			poll: true,
			extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: "crw"]], 
			submoduleCfg: [], 
			userRemoteConfigs: [[url: "https://github.com/redhat-developer/codeready-workspaces.git"]]])
		checkout([$class: 'GitSCM', 
			branches: [[name: "${branchToBuildCheTheia}"]], 
			doGenerateSubmoduleConfigurations: false, 
			poll: true,
			extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: "che-theia"]], 
			submoduleCfg: [], 
			userRemoteConfigs: [[url: "https://github.com/eclipse/che-theia.git"]]])
		installNPM()
		sh "export GITHUB_TOKEN=${GITHUB_TOKEN}"
		// sh 'printenv | sort'

		// TODO replace Alpine with UBI
		// sh "cp crw/dependencies/che-theia/dockerfiles/theia-dev/Dockerfile che-theia/dockerfiles/theia-dev/Dockefile"
		// sh "cp crw/dependencies/che-theia/dockerfiles/theia/Dockerfile che-theia/dockerfiles/theia/Dockefile"
		// TODO add more UBI Dockerfiles if needed (endpoint-runtime, remote-plugin-*)

		// CRW-360 use RH NPM mirror
		sh "cd che-theia; sed -i 's|https://registry.yarnpkg.com/|https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/|g' yarn.lock"

		// increase verbosity of yarn calls
		sh '''#!/bin/bash -xe 
		for d in $(find . -name package.json); do sed -i $d -e 's#yarn #yarn --verbose #g'; done"
		'''

		// TODO make this a for loop or split into stages
		//sh '''#!/bin/bash -xe //'''
		sh "cd che-theia && ./build.sh theia-dev theia --no-tests --build-args:GITHUB_TOKEN=${GITHUB_TOKEN},THEIA_VERSION=${che_theia_version} --tag:${che_theia_tag} --branch:${che_theia_branch} --git-ref:${che_theia_gitref}"
		// sh "cd che-theia/dockerfiles/theia-endpoint-runtime && ./build.sh --no-tests --build-args:GITHUB_TOKEN=${GITHUB_TOKEN},THEIA_VERSION=${che_theia_version} --tag:${che_theia_tag} --branch:${che_theia_branch} --git-ref:${che_theia_gitref}"
		// sh "cd che-theia/dockerfiles/remote-plugin-java8 && ./build.sh --no-tests --build-args:GITHUB_TOKEN=${GITHUB_TOKEN},THEIA_VERSION=${che_theia_version} --tag:${che_theia_tag} --branch:${che_theia_branch} --git-ref:${che_theia_gitref}"
		// sh "cd che-theia/dockerfiles/remote-plugin-openshift-connector-0.0.21 && ./build.sh --no-tests --build-args:GITHUB_TOKEN=${GITHUB_TOKEN},THEIA_VERSION=${che_theia_version} --tag:${che_theia_tag} --branch:${che_theia_branch} --git-ref:${che_theia_gitref}"

		// TODO verify this works & is archived correctly
		// tar up the node modules and other 3rd party deps from the generated containers so we can inject them into the Brew builds
		sh '''#!/bin/bash -xe 
		CONTAINERNAME="eclipse/che-theia-builder-e2e:${che_theia_tag}" && \
		CONTENT_TO_ARCHIVE="projects" && \
		PATHNAME="/tmp/che-theia/dockerfiles/theia-dev/target" && \
		TARNAME="$(echo ${CONTAINERNAME//:/--} | tr "/" "_")__${CONTENT_TO_ARCHIVE}.tgz" && \
		mkdir -p ${PATHNAME} && cd ${PATHNAME} && \
		docker run --name ${TARNAME} --rm --mount type=bind,source=${PATHNAME},target=/out ${CONTAINERNAME} /bin/bash -c "tar czf /out/${TARNAME} /${CONTENT_TO_ARCHIVE}" && \
		echo "Created ${PATHNAME}/${TARNAME}"
		//'''
		// TODO repeat for other builds

		// TODO verify this works & is archived correctly
		archiveArtifacts fingerprint: true, artifacts: "\
			/tmp/che-theia/dockerfiles/theia-dev/target/*.tgz, \
			che-theia/dockerfiles/theia-dev/generator/*.tgz, \
			che-theia/dockerfiles/theia/che-theia/*.tgz\
		"

		def descriptString="Build #${BUILD_NUMBER} (${BUILD_TIMESTAMP}) <br/> :: ${che_theia_version}, ${che_theia_tag}, ${che_theia_branch}"
		echo "${descriptString}"
		currentBuild.description="${descriptString}"
	}
}

// TODO enable downstream image builds
// timeout(120) {
// 	node("${node}"){ stage "Run get-sources-rhpkg-container-build"
// 		def QUAY_REPO_PATHs=(env.ghprbPullId && env.ghprbPullId?.trim()?"":("${SCRATCH}"=="true"?"":"server-rhel8"))

// 		def matcher = ( "${JOB_NAME}" =~ /.*_(stable-branch|master).*/ )
// 		def JOB_BRANCH= (matcher.matches() ? matcher[0][1] : "stable-branch")

// 		echo "[INFO] Trigger get-sources-rhpkg-container-build " + (env.ghprbPullId && env.ghprbPullId?.trim()?"for PR-${ghprbPullId} ":"") + \
// 		"with SCRATCH = ${SCRATCH}, QUAY_REPO_PATHs = ${QUAY_REPO_PATHs}, JOB_BRANCH = ${JOB_BRANCH}"

// 		// trigger OSBS build
// 		build(
// 		  job: 'get-sources-rhpkg-container-build',
// 		  wait: false,
// 		  propagate: false,
// 		  parameters: [
// 			[
// 			  $class: 'StringParameterValue',
// 			  name: 'GIT_PATH',
// 			  value: "containers/codeready-workspaces",
// 			],
// 			[
// 			  $class: 'StringParameterValue',
// 			  name: 'GIT_BRANCH',
// 			  value: "crw-2.0-rhel-8",
// 			],
// 			[
// 			  $class: 'StringParameterValue',
// 			  name: 'QUAY_REPO_PATHs',
// 			  value: "${QUAY_REPO_PATHs}",
// 			],
// 			[
// 			  $class: 'StringParameterValue',
// 			  name: 'SCRATCH',
// 			  value: "${SCRATCH}",
// 			],
// 			[
// 			  $class: 'StringParameterValue',
// 			  name: 'JOB_BRANCH',
// 			  value: "${JOB_BRANCH}",
// 			]
// 		  ]
// 		)
// 	}
// }
