---
displayName: Java Spring Boot
description: Java stack with OpenJDK 8, Maven 3.6.3 and Spring Boot Petclinic demo application
tags: ["Java", "OpenJDK", "Maven", "Spring Boot"]
icon: /images/type-snowdrop.svg
