---
displayName: NodeJS MongoDB
description: NodeJS stack with NPM 6.14.6, NodeJS 12.18.4 and MongoDB 3.6
tags: ["NodeJS", "NPM", "Express", "MongoDB", "UBI8"]
icon: /images/type-node.svg
links:
  v2: https://github.com/crw-samples/nodejs-mongodb-sample/tree/devspaces-3-rhel-8
