---
displayName: Tooling for Apache Camel K
description: Tooling to develop Integration projects with Apache Camel K
tags: ["RHEL8", "Apache Camel K", "Red Hat Fuse", "Integration"]
icon: /images/type-fuse.svg
globalMemoryLimit: 2850Mi
