---
displayName: Tooling for Apache Camel K
description: Tooling to develop Integration projects with Apache Camel K
tags: ["Apache Camel K", "Red Hat Fuse", "Integration", "UBI8"]
icon: /images/type-fuse.svg
