---
displayName: Java Maven
description: Java stack with OpenJDK 11, Maven 3.6.3 and Vert.x demo
tags: ["Java", "OpenJDK", "Maven", "Vert.x", "UBI8"]
icon: /images/type-vertx.svg
links:
  v2: https://github.com/crw-samples/vertx-health-checks-example-redhat/tree/devspaces-3.0-rhel-8
