---
displayName: Java Maven
description: Java stack with OpenJDK 11, Maven 3.6.3 and Vert.x demo
tags: ["Java", "OpenJDK", "Maven", "Vert.x", "UBI8"]
icon: /images/type-vertx.svg
globalMemoryLimit: 3186Mi
