---
displayName: Java 11 with JBoss EAP XP 3.0 Microprofile
description: Java stack with OpenJDK 11, Maven 3.6 and JBoss EAP XP 3.0
tags: ["Java", "OpenJDK", "Maven", "EAP", "Microprofile", "EAP XP", "RHEL8"]
icon: /images/type-jboss.svg
links:
  v2: https://github.com/devspaces-samples/microprofile-quickstart/tree/devspaces-3-rhel-8
