---
displayName: Java with JBoss EAP XP 3.0 Microprofile
description: Java stack with OpenJDK 11, Maven 3.6.2 and JBoss EAP XP 3.0
tags: ["rh-supported", "Java", "OpenJDK", "Maven", "EAP", "Microprofile", "EAP XP", "RHEL8"]
icon: /images/type-jboss.svg
