---
displayName: Node.js MongoDB
description: Node.js stack with NPM 8, Node.js 16 and MongoDB 3.6
tags: ["Node.js", "NPM", "Express", "MongoDB", "UBI8"]
icon: /images/type-node.svg
links:
  v2: https://github.com/devspaces-samples/nodejs-mongodb-sample/tree/devspaces-3.6-rhel-8
