---
displayName: Java 11 with Vert.x
description: Java stack with OpenJDK 11, Maven 3.6.3 and Vert.x booster
tags: ["Java", "OpenJDK", "Maven", "Vert.x", "UBI8", "no-airgap-support"]
icon: /images/type-vertx.svg
links:
  v2: https://github.com/devspaces-samples/vertx-http-example/tree/devspaces-3-rhel-8
