---
displayName: Java Lombok
description: Java stack with OpenJDK 11, Maven 3.6.3 and Lombok 1.18.18
tags: ["Java", "OpenJDK", "Maven", "Lombok", "UBI8"]
icon: /images/type-lombok.svg
links:
  v2: https://github.com/crw-samples/lombok-project-sample/tree/devspaces-3-rhel-8
