---
displayName: ".NET"
description: .NET stack with .NET Core SDK 3.1.103, Runtime, C# Language Support and Debugger
tags: ["Tech-Preview", ".NET", "C#", ".NET SDK", ".NET Runtime", "Netcoredbg", "Omnisharp", "UBI8"]
icon: /images/type-dotnet.svg
links:
  v2: https://github.com/crw-samples/dotnet-web-simple/tree/devspaces-3-rhel-8
