---
displayName: Java Lombok
description: Java Stack with Project Lombok
tags: ["Java", "OpenJDK", "Maven", "Lombok", "UBI8"]
icon: /images/type-lombok.svg
links:
  v2: https://github.com/devspaces-samples/lombok-project-sample/tree/devspaces-3.15-rhel-8
