---
displayName: Java 8 with Spring Boot
description: Java stack with OpenJDK 8, Maven 3.6.3 and Spring Boot Petclinic demo application
tags: ["Java", "OpenJDK", "Maven", "Spring Boot", "no-airgap-support"]
icon: /images/type-snowdrop.svg
links:
  v2: https://github.com/devspaces-samples/rest-http-example/tree/devspaces-3-rhel-8
