#!/usr/bin/env groovy

def installNPM(){
	def nodeHome = tool 'nodejs-10.15.3'
	env.PATH="${nodeHome}/bin:${env.PATH}"
	sh "node --version; npm --version"
}


timeout(120) {
	node("${node}"){ stage "Build ${extensionFolder}"
	  def extensionFolder = "${extensionPath}".substring(string.lastIndexOf('/') + 1);
		checkout([$class: 'GitSCM',
			branches: [[name: "${branchToBuildPlugin}"]],
			doGenerateSubmoduleConfigurations: false,
			poll: true,
			extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: "${extensionFolder}"]],
			submoduleCfg: [],
			userRemoteConfigs: [[url: "${extensionPath}"]]])

		sh "cd ${extensionFolder}"
		sh "npm --version"
		installNPM()
		sh "cd ${extensionFolder} && sudo npm install -g vsce && sudo npm install -g gulp && npm install && vsce package"

		echo "build finished"

		archiveArtifacts artifacts: '${extensionFolder}/*.vsix', fingerprint: true
	}
}
