---
displayName: Python
description: Python Stack with Python 3.6.8 and pip 9.0.3
tags: ["Python", "pip", "UBI8"]
icon: /images/type-python.svg
links:
  v2: https://github.com/crw-samples/python-hello-world/tree/devfilev2
