---
displayName: Red Hat Fuse
description: Red Hat Fuse stack with OpenJDK 8 and Maven 3.6.3
tags: ["Java", "OpenJDK", "Maven", "Red Hat Fuse", "UBI8"]
icon: /images/type-fuse.svg
globalMemoryLimit: 3328Mi
