---
displayName: Red Hat Fuse
description: Red Hat Fuse stack with OpenJDK 11 and Maven 3.6.3
tags: ["Java", "OpenJDK", "Maven", "Red Hat Fuse", "UBI8"]
icon: /images/type-fuse.svg
links:
  v2: https://github.com/crw-samples/fuse-rest-http-booster/tree/devspaces-3-rhel-8
