#!/usr/bin/env groovy

import groovy.transform.Field

// PARAMETERS for this pipeline:
// def FORCE_BUILD = "false"

def SOURCE_REPO = "eclipse/che-machine-exec" // upstream source repo from which to find and sync commits to pkgs.devel repo
def DWNSTM_REPO = "containers/codeready-workspaces-machineexec" // dist-git repo to use as target

@Field String SOURCE_BRANCH = "7.20.x" // upstream source repo branch from which to find and sync commits to pkgs.devel repo
@Field String DWNSTM_BRANCH = "crw-2.6-rhel-8" // target branch in dist-git repo, eg., crw-2.5-rhel-8
def SCRATCH = "false"
def PUSH_TO_QUAY = "true"
def QUAY_PROJECT = "machineexec" // also used for the Brew dockerfile params
def SYNC_FILES = "activity api auth build cfg client cloud-shell common exec exec-info filter kubeconfig mocks output shell vendor ws-conn compile.sh CONTRIBUTING.md devfile.yaml go.mod go.sum LICENSE main.go VERSION README.md"

def OLD_SHA=""
def HAS_CHANGED="false"

def buildNode = "rhel7-releng" // node label
timeout(120) {
	node("${buildNode}"){ stage "Sync repos"
    wrap([$class: 'TimestamperBuildWrapper']) {
      sh('curl -sSLO https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/' + DWNSTM_BRANCH + '/product/util.groovy')
      def util = load "${WORKSPACE}/util.groovy"
      cleanWs()
      CRW_VERSION = util.getCrwVersion(DWNSTM_BRANCH)
      println "CRW_VERSION = '" + CRW_VERSION + "'"
      util.installSkopeo("2.5") // (CRW_VERSION)
      withCredentials([string(credentialsId:'devstudio-release.token', variable: 'GITHUB_TOKEN'),
          file(credentialsId: 'crw-build.keytab', variable: 'CRW_KEYTAB')]) {
        util.bootstrap(CRW_KEYTAB)

        println "########################################################################################################"
        println "##  Clone and update github.com/${SOURCE_REPO}.git"
        println "########################################################################################################"
        util.cloneRepo("https://github.com/${SOURCE_REPO}.git", "${WORKSPACE}/sources", SOURCE_BRANCH)
        SOURCE_SHA = util.getLastCommitSHA("${WORKSPACE}/sources")

        // can't yet generate a PR against eclipse/che-* repos, and can't push directly
        // so check for a new base image but DO NOT commit/push/pull-request
        util.updateBaseImages("${WORKSPACE}/sources", DWNSTM_BRANCH, "-f rhel.Dockerfile --nocommit")

        println "########################################################################################################"
        println "##  Sync ${QUAY_PROJECT} to pkgs.devel"
        println "########################################################################################################"
        util.cloneRepo("ssh://crw-build@pkgs.devel.redhat.com/${DWNSTM_REPO}", "${WORKSPACE}/targetdwn", DWNSTM_BRANCH)
        OLD_SHA = util.getLastCommitSHA("${WORKSPACE}/targetdwn")
        println "Got OLD_SHA in targetdwn folder: " + OLD_SHA

        // rsync files in github to dist-git
        sh('''#!/bin/bash -xe
          SYNC_FILES="''' + SYNC_FILES + '''"
          for d in ${SYNC_FILES}; do
            if [[ -f ${WORKSPACE}/sources/${d} ]]; then
              rsync -zrlt ${WORKSPACE}/sources/${d} ${WORKSPACE}/targetdwn/${d}
            elif [[ -d ${WORKSPACE}/sources/${d} ]]; then
              # copy over the files
              rsync -zrlt ${WORKSPACE}/sources/${d}/* ${WORKSPACE}/targetdwn/${d}/
              # sync the directory and delete from targetdwn if deleted from source
              rsync -zrlt --delete ${WORKSPACE}/sources/${d}/ ${WORKSPACE}/targetdwn/${d}/
            fi
          done
        ''')

        sh('''#!/bin/bash -xe
          cp -f ${WORKSPACE}/sources/build/dockerfiles/rhel.Dockerfile ${WORKSPACE}/targetdwn/Dockerfile
          CRW_VERSION="''' + CRW_VERSION_F + '''"
          #apply patches
          sed -i ${WORKSPACE}/targetdwn/Dockerfile \
            -e "s#FROM registry.redhat.io/#FROM #g" \
            -e "s#FROM registry.access.redhat.com/#FROM #g"

          METADATA='ENV SUMMARY="Red Hat CodeReady Workspaces ''' + QUAY_PROJECT + ''' container" \\\r
    DESCRIPTION="Red Hat CodeReady Workspaces ''' + QUAY_PROJECT + ''' container" \\\r
    PRODNAME="codeready-workspaces" \\\r
    COMPNAME="''' + QUAY_PROJECT + '''-rhel8" \r
LABEL summary="$SUMMARY" \\\r
      description="$DESCRIPTION" \\\r
      io.k8s.description="$DESCRIPTION" \\\r
      io.k8s.display-name=\"$DESCRIPTION" \\\r
      io.openshift.tags="$PRODNAME,$COMPNAME" \\\r
      com.redhat.component="$PRODNAME-$COMPNAME-container" \\\r
      name="$PRODNAME/$COMPNAME" \\\r
      version="'${CRW_VERSION}'" \\\r
      license="EPLv2" \\\r
      maintainer="Nick Boldt <nboldt@redhat.com>" \\\r
      io.openshift.expose-services="" \\\r
      usage="" \r'

          echo -e "$METADATA" >> ${WORKSPACE}/targetdwn/Dockerfile

        ''')

        // push changes in github to dist-git
        util.updateBaseImages("${WORKSPACE}/targetdwn", DWNSTM_BRANCH, "--nocommit")
        sh('''#!/bin/bash -xe
          export KRB5CCNAME=/var/tmp/crw-build_ccache
          SYNC_FILES="''' + SYNC_FILES + '''"
          cd ${WORKSPACE}/targetdwn
          if [[ \$(git diff --name-only) ]]; then # file changed
            git add Dockerfile ${SYNC_FILES}
            # note this might fail if we're syncing from a tag vs. a branch
            git commit -s -m "[sync] Update from ''' + SOURCE_REPO + ''' @ ''' + SOURCE_SHA[0..7] + '''" Dockerfile ${SYNC_FILES}
            git push origin ''' + DWNSTM_BRANCH + ''' || true
            NEW_SHA=\$(git rev-parse HEAD) # echo ${NEW_SHA:0:8}
            echo "[sync] Updated pkgs.devel @ ${NEW_SHA:0:8} from ''' + SOURCE_REPO + ''' @ ''' + SOURCE_SHA[0..7] + '''"
          fi
        ''')
        NEW_SHA = util.getLastCommitSHA("${WORKSPACE}/targetdwn")
        if (OLD_SHA != NEW_SHA) { HAS_CHANGED="true" }

        println "########################################################################################################"
        println "##  Container Build"
        println "########################################################################################################"
        if (HAS_CHANGED == "true" || FORCE_BUILD == "true") {
          sh('''#!/bin/bash -xe
            for QRP in ''' + QUAY_PROJECT + '''; do
              QUAY_REPO_PATH=""; if [[ ''' + PUSH_TO_QUAY + ''' == "true" ]]; then QUAY_REPO_PATH="${QRP}-rhel8"; fi
              curl \
"https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/get-sources-rhpkg-container-build/buildWithParameters?\
token=CI_BUILD&\
cause=${QUAY_REPO_PATH}+respin+by+${BUILD_TAG}&\
GIT_BRANCH=''' + DWNSTM_BRANCH + '''&\
GIT_PATHs=containers/codeready-workspaces-${QRP}&\
QUAY_REPO_PATHs=${QUAY_REPO_PATH}&\
JOB_BRANCH=''' + CRW_VERSION + '''&\
FORCE_BUILD=true&\
SCRATCH=''' + SCRATCH + '''"
            done
          ''')
        } else {
          println "No changes upstream, nothing to commit"
        }

        NEW_SHA = util.getLastCommitSHA("${WORKSPACE}/targetdwn")
        println "Got NEW_SHA in targetdwn folder: " + NEW_SHA

        if (NEW_SHA.equals(OLD_SHA) && !FORCE_BUILD.equals("true")) {
          currentBuild.result='UNSTABLE'
        }
      } // withCredentials
    } // wrap
  } // node
} // timeout