---
displayName: Quarkus REST API
description: Quarkus stack with a default REST endpoint application sample
tags: ["Java", "OpenJDK", "Maven", "Quarkus", "UBI8"]
icon: /images/type-quarkus.svg
links:
  v2: https://github.com/devspaces-samples/quarkus-quickstarts/tree/devspaces-3.16-rhel-8
