---
displayName: Go
description: Stack with Go
tags: ["Tech-Preview", "Go", "Golang", "UBI8"]
icon: /images/type-go.svg
links:
  v2: https://github.com/crw-samples/golang-health-check/tree/devspaces-3-rhel-8
