= Deploying Che 7 to Minishift 1.34+

== Prerequisites

You need the latest link:https://github.com/minishift/minishift/releases[Minishift] and link:https://github.com/che-incubator/chectl/releases[chectl] releases.

Fetch them like this (or similar):

```
cd ~/bin
curl -sSL https://github.com/che-incubator/chectl/releases/download/20190724230954/chectl-linux -o chectl
chmod +x chectl
```

```
cd /tmp
curl -sSL https://github.com/minishift/minishift/releases/download/v1.34.1/minishift-1.34.1-linux-amd64.tgz -o minishift.tgz
tar xvzf minishift.tgz
mv minishift*/minishift ~/bin/
chmod +x ~/bin/minishift
```

== Procedure

. Start up minishift. (See link:building-crw.adoc#start-up-minishift[Start up Minishift] for some suggested default settings.)
+
```
minishift start
```

. Log in once startup is complete.
+
```
oc login 192.168.MY.IP:8433 -u system -p admin
```
+
[NOTE]
====
To watch the events and verify which images are pulled, see link:che7-minishift-images.adoc[this document] before performing the next step.
====

. Deploy Che to minishift using link:https://github.com/che-incubator/chectl/[`chectl`] and the link:https://github.com/eclipse/che-operator/[`che-operator`]:
+
```
chectl server:start -a operator -p minishift -n che
```
+
[NOTE]
====
You can also use the `-a minishift-addon` approach to deploy che, which uses a deployment configuration instead of an operator. However, this approach is *deprecated* as it does not support using a link:che7-custom-images-cr.adoc[custom resource] (eg., for air gap deployments). 

Also, if using Minishift 1.34.0 or earlier with the `minishift-addon`, you must fix the plugin registry URL to use the latest version:

```
oc set env dc/che CHE_WORKSPACE_PLUGIN__REGISTRY__URL=https://che-plugin-registry.openshift.io/v3
```

You can open the console for the che `minishift-addon` deployment to verify your change has been applied:

* https://192.168.YOUR.IP:8443/console/project/che/edit/dc/che

You should see:

```
CHE_WORKSPACE_PLUGIN__REGISTRY__URL = https://che-plugin-registry.openshift.io/v3
```
====

. Wait for redeployment to complete.

. Once running, you can see your Che instance here:
+
* http://che-che.192.168.YOUR.IP.nip.io/

. If you then add a new workspace, you can see even more images pulled in the openshift link:che7-minishift-images.adoc[event log].
