#
# Copyright (c) 2020-2024 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Plugin Registry - PR check - Build

on: 
  pull_request:
    paths:
    - 'dependencies/che-plugin-registry/**'

jobs:
  image-build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: dependencies/che-plugin-registry
    steps:
    - name: Clone source code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v1
      with:
        node-version: '18'

    - name: Login to the Red Hat Registry
      uses: azure/docker-login@83efeb77770c98b620c73055fbb59b2847e17dc0
      with:
        login-server: registry.redhat.io
        username: ${{ secrets.REGISTRY_REDHAT_IO_USERNAME }}
        password: ${{ secrets.REGISTRY_REDHAT_IO_PASSWORD }}

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

    - name: image-build
      run: |
        export SKIP_FORMAT=true
        export SKIP_LINT=true
        export SKIP_TEST=true
        BUILDER=docker ./build.sh --tag pr-check --offline
