#
# Copyright (c) 2020-2022 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Plugin Registry - Publish Registry Content Latest

on:
  push:
    branches:
      - crw-2-rhel-8
    paths:
      - 'dependencies/che-plugin-registry/**'

jobs:
  publish:
    name: publish
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: extract content
        run: |
          docker pull quay.io/crw/pluginregistry-rhel8:latest
          docker create --name pluginRegistry quay.io/crw/pluginregistry-rhel8:latest sh
          mkdir -p /tmp/crw-plugin-registry/content
          touch /tmp/crw-plugin-registry/content/.surgeignore
          echo "*.vsix" >> /tmp/crw-plugin-registry/content/.surgeignore
          docker cp pluginRegistry:/var/www/html/v3 /tmp/crw-plugin-registry/content/v3
          ls -a /tmp/crw-plugin-registry/content/v3
          docker rm -f pluginRegistry
          cp /tmp/crw-plugin-registry/content/v3/plugins/index.json /tmp/crw-plugin-registry/content/index.json
      - name: Publish to surge.sh
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: |
          sudo apt-get install tree
          npm install -g surge
          # generate tree index on all directories
          for directory in `find /tmp/crw-plugin-registry/content/ -type d`
            do
              (cd $directory && tree -H '.' -L 1 --noreport --charset utf-8 | sed '/<p class="VERSION">/,/<\/p>/d' > index.html)
           done
           # Make meta.yaml as index
           for file in $(find /tmp/crw-plugin-registry/content -name 'meta.yaml' -type f)
             do
               PARENT_DIR=$(dirname $file);
               cp ${PARENT_DIR}/meta.yaml ${PARENT_DIR}/index.html
             done
           export DEPLOY_DOMAIN=https://crw-plugin-registry-latest.surge.sh
           echo "DEPLOY_DOMAIN=$DEPLOY_DOMAIN" >> $GITHUB_ENV
           surge /tmp/crw-plugin-registry/content --domain $DEPLOY_DOMAIN
      - name: Publish to gh-pages
        run: |
          BUILD_DIR="/tmp/crw-plugin-registry/content"
          GH_PAGES_DIR="$PWD/gh-pages"
          GITHUB_REPO_NAME="codeready-workspaces"
          VERSION_DIR="latest"

          rm "$GH_PAGES_DIR" -rf;
          mkdir "$GH_PAGES_DIR"
          cd "$GH_PAGES_DIR"
          rm -rf che-plugin-registry
          git clone -b gh-pages "https://github.com/$GITHUB_REPOSITORY.git"
          cd "$GITHUB_REPO_NAME"
          [ -d "$VERSION_DIR" ] && git rm -r "$VERSION_DIR"
          rm -rf "$BUILD_DIR"/v3/resources
          cp -rf "$BUILD_DIR" "$VERSION_DIR"
          # Make meta.yaml as index
          while IFS= read -r -d '' file
          do
            PARENT_DIR=$(dirname "$file");
            cp "${PARENT_DIR}"/meta.yaml "${PARENT_DIR}"/index.json;
          done <   <(find . -name 'meta.yaml' -type f -print0)
          git add "$VERSION_DIR"
          git config user.email "crw-build@redhat.com"
          git config user.name "CRW Build"
          git diff-index --quiet HEAD || git commit -m "publish registry $VERSION_DIR - $(date)" -s

          git push "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" gh-pages
          echo "Checkout the published plugin registry at https://$GITHUB_ACTOR.github.io/$GITHUB_REPO_NAME/$VERSION_DIR/v3/plugins/"
