#
# Copyright (c) 2024 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Check new versions of VSIX extensions

on:
  schedule:
    - cron: '0 0 1 * *' # Run at midnight (00:00) on the 1st day of every month

jobs:
  Check-new-extensions-versions:
    runs-on: ubuntu-20.04

    steps:

    - name: Clone source code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        token: ${{secrets.CRW_BUILD_TOKEN}}

    - name: Validate content
      run: |
        cd dependencies/che-plugin-registry/build/scripts
        ./update_extensions_versions.sh

    - name: Verify Changed files
      uses: tj-actions/verify-changed-files@v19
      id: verify-changed-files
      with:
        files: dependencies/che-plugin-registry/openvsx-sync.json
        
    - name: Create Pull Request
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      run: |
        # Set up git configuration
        export GITHUB_TOKEN=${{ secrets.CRW_BUILD_TOKEN }}
        git config user.email "nickboldt+devstudio-release@gmail.com"
        git config user.name "devstudio-release"

        # Create a new branch
        git checkout -b new-extension-version-branch

        # Add and commit changes
        git add .
        git commit -m "Auto-generated changes; update vsix extensions versions"

        # Push changes to the remote repository
        git push origin new-extension-version-branch

        # Create a pull request
        gh pr create --title "chore: Auto-generated PR to update extnesions versions" --body "This pull request was automatically generated by GitHub Actions" --base devspaces-3-rhel-8
