---
displayName: Java 11 with Maven
description: Java stack with OpenJDK 11, Maven 3.6.3 and Vert.x demo
tags: ["Java", "OpenJDK", "Maven", "Vert.x", "UBI8", "no-airgap-support"]
icon: /images/type-vertx.svg
links:
  v2: https://github.com/devspaces-samples/vertx-health-checks-example-redhat/tree/devspaces-3-rhel-8
